### ISSUE TITLE
训练的时候遇到这个错误

### ISSUE THREAD

**Issue by zouhuigang** [dream80/DeepFaceLab_Colab#30]
#@title 训练模型
Model = "SAEHD" #@param ["SAEHD","AMP","Quick96","XSeg"]
%cd $deepfacelab_cloab
cmd = "main.py train --training-data-src-dir ../workspace/data_src/aligned --training-data-dst-dir ../workspace/data_dst/aligned --model-dir ../workspace/model --model "+Model+" --no-preview"
!python $cmd
Model:

SAEHD
more_horiz
/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab
Running trainer.

[new] No saved models found. Enter a name of a new model : aa
aa

Model first run.

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : Tesla T4

[0] Which GPU indexes to choose? : 0
0

[0] Autobackup every N hour ( 0..24 ?:help ) : 
0
[n] Write preview history ( y/n ?:help ) : 
n
[0] Target iteration : 0
0
[n] Flip SRC faces randomly ( y/n ?:help ) : y
[y] Flip DST faces randomly ( y/n ?:help ) : y
[8] Batch_size ( ?:help ) : 8
8
[128] Resolution ( 64-640 ?:help ) : 128
128
[f] Face type ( h/mf/f/wf/head ?:help ) : f
f
[liae-ud] AE architecture ( ?:help ) : 
liae-ud
[256] AutoEncoder dimensions ( 32-1024 ?:help ) : 
256
[64] Encoder dimensions ( 16-256 ?:help ) : 
64
[64] Decoder dimensions ( 16-256 ?:help ) : 
64
[22] Decoder mask dimensions ( 16-256 ?:help ) : 
22
[n] Eyes and mouth priority ( y/n ?:help ) : 
n
[n] Uniform yaw distribution of samples ( y/n ?:help ) : 
n
[n] Blur out mask ( y/n ?:help ) : 
n
[y] Place models and optimizer on GPU ( y/n ?:help ) : 
y
[y] Use AdaBelief optimizer? ( y/n ?:help ) : 
y
[n] Use learning rate dropout ( n/y/cpu ?:help ) : 
n
[y] Enable random warp of samples ( y/n ?:help ) : 
y
[0.0] Random hue/saturation/light intensity ( 0.0 .. 0.3 ?:help ) : 
0.0
[0.0] GAN power ( 0.0 .. 5.0 ?:help ) : 
0.0
[0.0] Face style power ( 0.0..100.0 ?:help ) : 
0.0
[0.0] Background style power ( 0.0..100.0 ?:help ) : 
0.0
[none] Color transfer for src faceset ( none/rct/lct/mkl/idt/sot ?:help ) : 
none
[n] Enable gradient clipping ( y/n ?:help ) : 
n
[n] Enable pretraining mode ( y/n ?:help ) : 
n

Initializing models: 100% 5/5 [00:01<00:00,  3.42it/s]
Loaded 654 packed faces from /content/drive/MyDrive/DeepFaceLab/workspace/data_src/aligned
Loaded 1449 packed faces from /content/drive/MyDrive/DeepFaceLab/workspace/data_dst/aligned
Process Process-2:
Traceback (most recent call last):
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleProcessor.py", line 106, in process
    warp_params = imagelib.gen_warp_params(resolution,
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/core/imagelib/warp.py", line 146, in gen_warp_params
    random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/core/joblib/SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample 00162_0.jpg. Error: Traceback (most recent call last):
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleProcessor.py", line 106, in process
    warp_params = imagelib.gen_warp_params(resolution,
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/core/imagelib/warp.py", line 146, in gen_warp_params
    random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

Process Process-3:
Traceback (most recent call last):
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleProcessor.py", line 106, in process
    warp_params = imagelib.gen_warp_params(resolution,
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/core/imagelib/warp.py", line 146, in gen_warp_params
    random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/core/joblib/SubprocessGenerator.py", line 54, in process_func
    gen_data = next (self.generator_func)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleGeneratorFace.py", line 136, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample 00111_0.jpg. Error: Traceback (most recent call last):
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleGeneratorFace.py", line 134, in batch_func
    x, = SampleProcessor.process ([sample], self.sample_process_options, self.output_sample_types, self.debug, ct_sample=ct_sample)
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/samplelib/SampleProcessor.py", line 106, in process
    warp_params = imagelib.gen_warp_params(resolution,
  File "/content/drive/MyDrive/DeepFaceLab/DeepFaceLab_Colab/core/imagelib/warp.py", line 146, in gen_warp_params
    random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

**Comment by zouhuigang** [comment]
已经解决了
